name: simple_dart_mcp_server
description: A very basic MCP (Model Context Protocol) server for Dart.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.8.0-1.0.dev

dependencies:
  web_socket_channel: ^3.0.2

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
